# Generated by Django 3.0 on 2020-02-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='email_content',
            field=models.TextField(default='Content'),
        ),
        migrations.AddField(
            model_name='email',
            name='email_subject',
            field=models.CharField(default='Subject', max_length=250),
        ),
    ]
