# Generated by Django 3.0 on 2020-02-23 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_auto_20200220_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='email_content',
        ),
        migrations.RemoveField(
            model_name='email',
            name='email_subject',
        ),
    ]
